[build]
target = "target.json"

[target.i686-unknown-none]
linker = "i686-elf-gcc"
rustflags = [
    "-C", "link-arg=-Tlinker.ld",
    "-C", "link-arg=-nostdlib",
    "-C", "link-arg=-ffreestanding",
    "-C", "force-unwind-tables=no",
]

[unstable]
build-std = ["core", "compiler_builtins"]